#workflowの名前
name: function-testing

#実行タイミング
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: print pwd
        run: pwd
      - users: actions/checkout@v2
      - name: run unit test
        run: |
          yarn install
          yarn test
